application: wave-samples-gallery
version: 4 
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: robots\.txt

- url: /static
  static_dir: static
  
- url: /moderate
  login: required
  script: projectgallery.py

- url: /.*
  script: projectgallery.py
