application: people-finder-demo
version: 1 
runtime: python
api_version: 1

handlers:
- url: /_wave/.*
  script: robot.py

- url: /web/.*
  script: robot.py

- url: /static
  static_dir: static

- url: /.*
  script: main.py

