application: ripple-bot
version: 1
runtime: python
api_version: 1

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /installer.xml.*
  static_files: installer.xml
  upload: installer.xml
  mime_type: text/xml

- url: /gadget_follow.xml.*
  static_files: gadget_follow.xml
  upload: gadget_follow.xml
  mime_type: text/xml

- url: /_wave/.*
  script: wave.py

- url: /service/.*
  script: main.py
