application:  maildigester-bot
version:      1
runtime:      python
api_version:  1

inbound_services:
- mail

handlers:
- url: /_wave/.*
  script: handler.py

- url: /_ah/mail/.*
  script: handler.py
